# version: '3'
# services:
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: djangodockerapp
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: adm1n@123
#     ports:
#       - '5432:5432'
#     volumes:
#       - db_data:/var/lib/postgresql/data/

#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: python manage.py runserver 0.0.0.0:8080
#     volumes:
#       - .:/code
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db

# volumes:
#   db_data:

version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=lambda_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=roOt@5